name: Absensi Otomatis

on:
  schedule:
   # Senin 08.00 WIB (Irwandi)
    - cron: '0 1 * * 1'

    # Selasa 08.00 WIB (Dr. Ir. Kahlil)
    - cron: '0 1 * * 2'

    # Selasa 14.00 WIB (Dr. Khairun Saddami)
    - cron: '0 7 * * 2'

    # Rabu 14.00 WIB (Dr. Ir. Yunidar, Dr. Auliyaa Raaf)
    - cron: '0 7 * * 3'

    # Kamis 08.00 WIB (Rizka Ramadhana)
    - cron: '0 1 * * 4'

    # Kamis 14.00 WIB (Dr. Ir. Kahlil)
    - cron: '0 7 * * 4'

    # Jumat 14.00 WIB (Ir. Maya Fitria)
    - cron: '0 7 * * 5'

    # Jumat 16.35 WIB (Dr. Ir. Kahlil)
    - cron: '35 9 * * 5'
  workflow_dispatch:

jobs:
  absen:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout repo
        uses: actions/checkout@v4

      - name: 2. Setup Chrome
        uses: browser-actions/setup-chrome@latest

      - name: 3. Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: 4. Install dependencies
        run: pip install selenium ddddocr python-dotenv

      - name: 5. Jalankan absen_runner.py
        env:
          NPM: ${{ secrets.NPM }}
          PASSWORD: ${{ secrets.PASSWORD }}
          NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
        run: python -u absen_runner.py
